movie_recommendation/urls.py
from django.urls import path , include
from . import views

app_name = 'movie_recommendation'

urlpatterns = [
    
    path('', views.index , name = 'home' ),
    path('search/', views.search , name = 'search' ),
    path('reset/', views.reset , name = 'reset' ),
]

theRecommender/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_recommendation.urls') , name='movie_recommendation'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_recommendation/models.py
from django.db import models

# Create your models here.

movie_recommendation/views.py
from django.shortcuts import render, redirect ,get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy ,reverse
from . import recommendmodel as mdl
import random

length = 0
search_data = []
data_main = []

def reset(request):
    global length , search_data , data_main
    request.session['sea'] = []
    length=0
    search_data=[]
    data_main=[]
    return redirect('movie_recommendation:home')


def index(request):
    
    context = {
        'data': mdl.tmdb_popular()
    }
    return render(request , 'movie_recommendation/index.html' , context=context)



def search(request):
    global length , search_data , data_main
    search_word = ''
    data = []
    
    if request.method == "POST":
        search_word = request.POST["search_word"]
        
        if(search_word in search_data):
            context = {
                'data': data_main,
                }
            return render(request , 'movie_recommendation/search.html' , context = context)
        #----------- Pass through ML model
        data = mdl.recommend_pro(search_word)
        
        if(data != None):
            data_main.extend(data[:4])
            search_data.append(search_word)
            request.session['sea'] = search_data
            length +=1
            data_main = [i for i in data_main if i not in search_data]
            if(len(data_main)>8):
                random.shuffle(data_main)
            context = {
                'data': data_main,
                }
        else:
            context = {
                'data': 'None',
            }
    
    return render(request , 'movie_recommendation/search.html' , context = context)
        
        

movie_recommendation/templates/movie_recommendation/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "movie_recommendation/css/bootstrap.min.css" %}">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "movie_recommendation/css/base.css" %}">
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&display=swap" rel="stylesheet"> 
    {% block userstyle %}
    {% endblock userstyle %}
    <title>Movie Recommender</title>
</head>

<body style="background:url('{% static "movie_recommendation/res/popcorn.jpg" %}');">
        <div style="background-color: rgba(0, 0, 0, 0.616);color:white;font-weight:bolder;font-size:50px;text-align:center;margin-right:20px;font-family: 'Amatic SC', cursive;">
            Movie Wizard
        </div>
        <div class="jumbotron" >
            <div class="top">
                <ul>
                    <li class="item"><a href="https://www.instagram.com/rjnepal.nepal/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    <li class="item"><a href="https://github.com/rohanjhanepal/"><i class="fa fa-github" aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <form action="{% url 'movie_recommendation:search' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <div class="row">
                    <div class="col-12">
                        <input type="text" placeholder="input your fav movie name" name="search_word" class="form-control" style="color:white">
                    </div>
                    <div class="col-12">
                        <button type="submit" class="newPrime">
                            <i class="fa fa-search" aria-hidden="true"></i>

                        </button>
                        <a href="{% url 'movie_recommendation:reset' %}" class="subtext"> Reset </a>
                    </div>
                  </div> 
                </div>
            </form>
        </div>

    <div class="container">
        {% block content %} 
        {% endblock content %}
    </div>









    <div class="loader-wrapper">
        <span class="loader"><span class="loader-inner"></span></span>
    </div>
    <script src="{% static "movie_recommendation/js/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "movie_recommendation/js/bootstrap.min.js" %}" type="text/javascript"></script>

    <script> 
        $(window).on("load",function(){
            $(".loader-wrapper").fadeOut("slow");
        });
    </script>
    {% block userscript %}
    {% endblock userscript %}
</body>

movie_recommendation/templates/movie_recommendation/index.html
{% extends 'movie_recommendation/base.html' %}
{% load custom_actions %}



{% block content %}
 <h4 style="color:white;text-align:center;font-weight:800px;border-bottom:1px solid white">Popular This Month</h4>
    <div class="row">
   {% for i in data %}
  <div class="col col-lg-4 col-sm-12 col-md-6">
    <div class="card" style="width: 18rem;background:rgba(255, 255, 255, 0.712);">
        <img src="{{ i.poster }}" class="card-img-top" alt="Movie Poster">
        <div class="card-body">
            <h5 class="card-title">{{ i.title }}</h5>
            <div style="width: 100%;background-color:rgba(243, 33, 68, 0.555);;">
                <div style="height:30px;text-align: right;padding-top: 2px;padding-bottom: 20px;color: white;width: {{ i.vote|mul }}%;background-color:rgba(243, 33, 68, 0.979);">{{ i.vote }}/10</div>
            </div>
            <br>
            <a href="{{ i.title|more }}" class="btn btn-outline-danger">More</a>
        </div>
    </div>
   </div>
   {% endfor %}
   </div>

{% endblock content %}

movie_recommendation/templates/movie_recommendation/search.html
{% extends 'movie_recommendation/base.html' %}
{% load custom_actions %}



{% block content %}

{% for i in request.session.sea %}
   <span class="badge badge-secondary">{{ i }}</span> 
{% endfor %}

<br> <br>
<!--    'title'   
        'overview'
        'poster'  
        'id'      
        'vote'    -->
        
{% if data != 'None' %}
    <div class="row">
   {% for i in data %}
  <div class="col col-lg-4 col-sm-12 col-md-6">
    <div class="card" style="width: 18rem;background:rgba(255, 255, 255, 0.712);">
        <img src="{{ i.poster }}" class="card-img-top" alt="Movie Poster">
        <div class="card-body">
            <h5 class="card-title">{{ i.title }}</h5>
            <p class="card-text">{{ i.overview }}</p>
            <div style="width: 100%;background-color:rgba(243, 33, 68, 0.555);;">
                <div style="height:30px;text-align: right;padding-top: 2px;padding-bottom: 20px;color: white;width: {{ i.vote|mul }}%;background-color:rgba(243, 33, 68, 0.979);">{{ i.vote }}/10</div>
            </div>
            <br>
            <a href="{{ i.title|more }}" class="btn btn-outline-danger">More</a>
        </div>
    </div>
   </div>
   {% endfor %}
   </div>

{% else %}
    <h2> No such movies </h2>
    <p> The keyword must be exact movie name from google </p>
{% endif %}
    

<br>

<div class="loader-wrapper">
        <span class="loader"><span class="loader-inner"></span></span>
    </div>

{% endblock content %}